logging:
  level:
    org:
      springframework: DEBUG

mongodb:
  client: mongodb://localhost:27017
  name: realEstate

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: realestate

  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/realEstate'
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  profiles:
    active: dev
jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000
  secretKey: fast-campus.simple_sns_2022_secret_key
  refresh:
    expiration: 604800000
    header: Refresh-Token
  access:
    header: Authorization
    expiration: 604800000


cloud:
  aws:
    s3:
      bucket: inho
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


chatgpt:
  api-key: ${CHATGPT_API_KEY}
  model: text-davinci-003
openai:
  url:
    model: https://api.openai.com/v1/models
    model-list: https://api.openai.com/v1/models/
    legacy-prompt: https://api.openai.com/v1/completions
    prompt: https://api.openai.com/v1/chat/completions
image:
  save_path : ./images
api:
  building-key: ${GET_BUILDING_API_KEY}
  land-key: ${GET_LAND_API_KEY}